### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Domosiqua** [yiweizhi-github/three_kingdoms_kill#1]
rot@ubuntu:~/桌面/three_kingdoms_kill-master$ lua main.lua
lua: error loading module 'game' from file './game.lua':
	./game.lua:120: '=' expected near 'continue'
stack traceback:
	[C]: ?
	[C]: in function 'require'
	main.lua:4: in main chunk
	[C]: ?
	
	
	我的lua版本为5.1.5 
        操作系统为Ubuntu 报错如上

**Comment by yiweizhi-github** [comment]
要lua5.2及以上，不然不支持goto语法
